// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAilYuKTuFmiT_O9LVIUaOd4LOziSolZiY',
    appId: '1:171117236402:web:79d9af8f2ef5f6481079ab',
    messagingSenderId: '171117236402',
    projectId: 'pentas-a2f19',
    authDomain: 'pentas-a2f19.firebaseapp.com',
    databaseURL: 'https://pentas-a2f19-default-rtdb.firebaseio.com',
    storageBucket: 'pentas-a2f19.firebasestorage.app',
    measurementId: 'G-66BRC4GJBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm7PfkSnLTUTihemZs8Fx1022CrR0dIsQ',
    appId: '1:171117236402:android:a285358491ea82b41079ab',
    messagingSenderId: '171117236402',
    projectId: 'pentas-a2f19',
    databaseURL: 'https://pentas-a2f19-default-rtdb.firebaseio.com',
    storageBucket: 'pentas-a2f19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBCCZhq3L3fSQtNLimoboRBWdFvAk-bS0',
    appId: '1:171117236402:ios:d314915ad69dbd801079ab',
    messagingSenderId: '171117236402',
    projectId: 'pentas-a2f19',
    databaseURL: 'https://pentas-a2f19-default-rtdb.firebaseio.com',
    storageBucket: 'pentas-a2f19.firebasestorage.app',
    iosBundleId: 'com.example.pentas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBCCZhq3L3fSQtNLimoboRBWdFvAk-bS0',
    appId: '1:171117236402:ios:d314915ad69dbd801079ab',
    messagingSenderId: '171117236402',
    projectId: 'pentas-a2f19',
    databaseURL: 'https://pentas-a2f19-default-rtdb.firebaseio.com',
    storageBucket: 'pentas-a2f19.firebasestorage.app',
    iosBundleId: 'com.example.pentas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAilYuKTuFmiT_O9LVIUaOd4LOziSolZiY',
    appId: '1:171117236402:web:8e249d9307e54f201079ab',
    messagingSenderId: '171117236402',
    projectId: 'pentas-a2f19',
    authDomain: 'pentas-a2f19.firebaseapp.com',
    databaseURL: 'https://pentas-a2f19-default-rtdb.firebaseio.com',
    storageBucket: 'pentas-a2f19.firebasestorage.app',
    measurementId: 'G-F32RLVDRL5',
  );

}